# Generated by Django 4.2.2 on 2023-07-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.EmailField(max_length=254)),
                ('uname', models.CharField(max_length=100)),
                ('mno', models.CharField(max_length=15)),
                ('pswd', models.CharField(max_length=20)),
                ('cpswd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'studenttb',
            },
        ),
    ]
