# Generated by Django 4.2.2 on 2023-07-10 08:27

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_final_hs_remove_student_id_alter_student_eid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(default=builtins.id, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='eid',
            field=models.EmailField(max_length=100),
        ),
    ]
