# Generated by Django 4.2.2 on 2023-07-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_id_alter_student_eid'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eid', models.EmailField(max_length=100)),
                ('uname', models.CharField(max_length=100)),
                ('mno', models.CharField(max_length=15)),
                ('pswd', models.CharField(max_length=20)),
                ('cpswd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'studentttb',
            },
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
