# Generated by Django 4.2.2 on 2023-07-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_table_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.EmailField(max_length=100)),
                ('uname', models.CharField(max_length=100)),
                ('mno', models.CharField(max_length=15)),
                ('pswd', models.CharField(max_length=20)),
                ('cpswd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'studenttb',
            },
        ),
        migrations.DeleteModel(
            name='student_table',
        ),
    ]
