# Generated by Django 4.2.2 on 2023-07-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_delete_student_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='eid',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
